# Site settings
author: Steve Womble
title: Things That Matter When You Are Learning Programming
header-img: img/home-bg.png
email: swomble@aol.com
copyright_name: Steve Womble
description: > # this means to ignore newlines until "baseurl:"
  My Thoughts & Observations
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  djsteve33

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
